@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

scale 750 width
package backend.service <<Node>> {
  class Class1
}

package backend.config <<Rectangle>> {
  class Class2
}

package backend.domain <<Folder>> {
  class Class3
}

package backend <<Frame>> {
  class Class4
}

package backend.http <<Cloud>> {
  class Class5
}

package backend.repositories.entities <<Database>> {
  class Class6
}

@enduml